In [1]:
import numpy as np

In [2]:
products=["Laptop","Mobile","Tablet"]
regions=["Chennai","Delhi","Mumbai"]
years=[2023,2024]

In [3]:
sales=np.array([[[120,150],[90,110],[70,95]],[[200,240],[180,210],[150,190]],[[80,100],[60,75],[50,65]]])

In [4]:
print(sales.shape)

(3, 3, 2)


In [5]:
def dice_cube(cube,p,r,y):
    return cube[np.ix_(p,r,y)]

In [6]:
rollup=np.sum(sales,axis=2)
print(rollup)

[[270 200 165]
 [440 390 340]
 [180 135 115]]


In [7]:
drill=sales[:,:,1]
print(drill)

[[150 110  95]
 [240 210 190]
 [100  75  65]]


In [8]:
class OLAPCube:
    def __init__(self,cube):
        self.cube=cube

    def slice(self,axis,index):
        return np.take(self.cube,index,axis=axis)

    def dice(self,p,r,y):
        return self.cube[np.ix_(p,r,y)]

    def rollup(self,axis):
        return np.sum(self.cube,axis=axis)

    def drilldown(self,axis,index):
        return np.take(self.cube,index,axis=axis)

cube=OLAPCube(sales)

In [9]:
cube=OLAPCube(sales)

print("========== SLICE OPERATION ==========")
print(cube.slice(axis=1,index=0))

print("\n========== DICE OPERATION ==========")
print(cube.dice([0,1],[0,2],[1]))

print("\n========== ROLL-UP OPERATION ==========")
print(cube.rollup(axis=2))

print("\n========== DRILL-DOWN OPERATION ==========")
print(cube.drilldown(axis=2,index=1))

========== SLICE OPERATION ==========
[[120 150]
 [200 240]
 [ 80 100]]

========== DICE OPERATION ==========
[[[150]
  [ 95]]

 [[240]
  [190]]]

========== ROLL-UP OPERATION ==========
[[270 200 165]
 [440 390 340]
 [180 135 115]]

========== DRILL-DOWN OPERATION ==========
[[150 110  95]
 [240 210 190]
 [100  75  65]]
